name: Update Daily Billboard Songs

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 7 * * *'  # Every day at 7:00 AM UTC

jobs:
  update-song:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install billboard-top-100
        run: npm install billboard-top-100

      - name: Run fetchBillboardSongs
        run: node fetchBillboardSongs.js

      - name: Commit Updated Songs
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add data/todaysSongs.json
          git commit -m "🎶 Daily update: Top songs from 10/20/30/40/50 years ago" || echo "No changes to commit"
          git push
