name: Update Daily Billboard Song

on:
  schedule:
    - cron: '0 7 * * *'  # Runs daily at 7:00 AM UTC
  workflow_dispatch:     # Allow manual trigger too

jobs:
  update-song:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Billboard Package
        run: npm install billboard-top-100

      - name: Run Song Fetch Script
        run: node fetchBillboardSong.js

      - name: Commit and Push Updated Song
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add data/todaysSong.json
          git commit -m "🔁 Auto-update song of the day" || echo "No changes to commit"
          git push
